### PR TITLE
Add the ability to generate configs from CSV files

### PR DESCRIPTION
**Pull request by ibacher**
Also generates random seeds where approriate

### CODE REVIEW

**Comment by ibacher** [comment]
bors ping

**Comment by DilumAluthge** [comment]
@ibacher You can drop support for Julia 0.7 if you want.

**Comment by ibacher** [comment]
Yeah, was just thinking I would do that… Might roll them over to Julia 1.1 though.

**Comment by DilumAluthge** [comment]
I wouldn’t drop support for both 0.7 and 1.0 at the same time. Generally the Julia General Registry maintainers don’t like it when you drop support for more than one version of Julia in a single release.

I’d recommend the following sequence of events:

1. Drop support for 0.7 and merge this PR,
2. Bump the major component of the version number in Project.toml.
3. Make a new release with Registrator (https://github.com/JuliaRegistries/Registrator.jl)
4. Drop support for 1.0.
5. Bump the major version number again.
6. Make another release with Registrator

**Comment by ibacher** [comment]
Oh no! To be clear, I wasn't going to drop 1.0. I was just going to add testing against 1.1!

**Comment by DilumAluthge** [comment]
Ahhhh I see. Yes that’s a good idea!

**Comment by DilumAluthge** [comment]
You can also add “1.2”. It’ll point to the release candidate.

**Comment by DilumAluthge** [comment]
Bors r+

**Pull request merged**
