### PR TITLE
Update to work under Julia 1.2

### PR DESCRIPTION
**Pull request by ibacher**

### CODE REVIEW

**Comment by ibacher** [comment]
bors merge+

**Comment by DilumAluthge** [comment]
Also, I just realized that `bors merge` is sufficient. We don’t need to add the `+` at the end.

**Comment by DilumAluthge** [comment]
bors merge

**Comment by DilumAluthge** [comment]
So, the failures on Windows on 1.3 and 1.4 are due to a known issue with 7z on Windows.

But I have no idea why we are getting failures on 1.0.

**Comment by ibacher** [comment]
I think it’s only failing on 1.3 and 1.4 on Windows? If that’s a known issue, I’ll just update the Travis config to allow those failures.

**Comment by ibacher** [comment]
bors merge

**Pull request merged**
