### PR TITLE
Use `CSV.printheader()` instead of `CSV.write()`

### PR DESCRIPTION
**Pull request by ibacher**
CSV.jl was updated so that `CSV.write()` takes new parameters. In the process, `CSV.printheader()` was added. Since we were only calling `CSV.write()` to print the header line, it seems logical to use that
method instead.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@ibacher Travis is also failing on this pull request.

 It may be that the Travis failures are not related to either pull request. In that case, the Travis failures will need to be fixed first, and then once Travis is passing we can merge your two pull requests.

**Comment by ibacher** [comment]
The Travis failures here are due to an error in the version of CSV.jl packaged for Julia 1.0+. I submitted a separate PR to CSV.jl ([#466](https://github.com/JuliaData/CSV.jl/pull/466)) which addresses the issue. Unfortunately, since that hasn't been packaged into a release yet, hence the failures.

**Comment by DilumAluthge** [comment]
I’ll ask them if they can tag a new release

**Comment by DilumAluthge** [comment]
Alright let's re-run Travis on this PR

**Comment by DilumAluthge** [comment]
@ibacher We need to disable `semantic-release` (it is not compatible with the new Registrator+Tagbot system for tagging new releases of Julia packages).

Can you comment out lines 27 through 39 of [this file](https://github.com/ibacher/DeIdentification.jl/blob/csv_0.5/.travis.yml)?

**Pull request merged**
